//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneShoppingList.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneShoppingList.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help and about.
        /// </summary>
        public static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft account (live ID).
        /// </summary>
        public static string accountName {
            get {
                return ResourceManager.GetString("accountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string addButtonText {
            get {
                return ResourceManager.GetString("addButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add items manually.
        /// </summary>
        public static string addItemManually {
            get {
                return ResourceManager.GetString("addItemManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new product.
        /// </summary>
        public static string addProductTitle {
            get {
                return ResourceManager.GetString("addProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new shopping path.
        /// </summary>
        public static string addShopPageTitle {
            get {
                return ResourceManager.GetString("addShopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string allShopsLabel {
            get {
                return ResourceManager.GetString("allShopsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string allTitle {
            get {
                return ResourceManager.GetString("allTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE SHOPPING LIST.
        /// </summary>
        public static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attention.
        /// </summary>
        public static string attentionText {
            get {
                return ResourceManager.GetString("attentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basket.
        /// </summary>
        public static string basketButtonText {
            get {
                return ResourceManager.GetString("basketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopping basket.
        /// </summary>
        public static string basketPageTitle {
            get {
                return ResourceManager.GetString("basketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancelButtonText {
            get {
                return ResourceManager.GetString("cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category &apos;{0}&apos; already exists. Do you want to merge the two categories?.
        /// </summary>
        public static string categoryMergeDialog {
            get {
                return ResourceManager.GetString("categoryMergeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check items in lists.
        /// </summary>
        public static string checkInList {
            get {
                return ResourceManager.GetString("checkInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear shopping list.
        /// </summary>
        public static string clearListMenu {
            get {
                return ResourceManager.GetString("clearListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string defaultCategory {
            get {
                return ResourceManager.GetString("defaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/EN-DefaultItemList.json.
        /// </summary>
        public static string defaultItemList {
            get {
                return ResourceManager.GetString("defaultItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/EN-DefaultShopList.json.
        /// </summary>
        public static string defaultShopList {
            get {
                return ResourceManager.GetString("defaultShopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pcs.
        /// </summary>
        public static string defaultUnit {
            get {
                return ResourceManager.GetString("defaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string deleteButtonText {
            get {
                return ResourceManager.GetString("deleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete {0}..
        /// </summary>
        public static string deleteElementConfirmation {
            get {
                return ResourceManager.GetString("deleteElementConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to clear your shopping list..
        /// </summary>
        public static string deleteListConfirmation {
            get {
                return ResourceManager.GetString("deleteListConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete shopping path.
        /// </summary>
        public static string deleteShopText {
            get {
                return ResourceManager.GetString("deleteShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move down.
        /// </summary>
        public static string downText {
            get {
                return ResourceManager.GetString("downText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping List.
        /// </summary>
        public static string emailSubject {
            get {
                return ResourceManager.GetString("emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string favButtonText {
            get {
                return ResourceManager.GetString("favButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string favoritesTitle {
            get {
                return ResourceManager.GetString("favoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW WOULD YOU LIKE TO START?.
        /// </summary>
        public static string howToStart {
            get {
                return ResourceManager.GetString("howToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string importButton {
            get {
                return ResourceManager.GetString("importButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start with a small database?.
        /// </summary>
        public static string importDescription {
            get {
                return ResourceManager.GetString("importDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import some sample data.
        /// </summary>
        public static string importHeader {
            get {
                return ResourceManager.GetString("importHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It contains usual products: Milk, Butter, Apples, ....
        /// </summary>
        public static string importPicker {
            get {
                return ResourceManager.GetString("importPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial setup.
        /// </summary>
        public static string initialSetupPageTitle {
            get {
                return ResourceManager.GetString("initialSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  items.
        /// </summary>
        public static string itemsName {
            get {
                return ResourceManager.GetString("itemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recent.
        /// </summary>
        public static string latestTitle {
            get {
                return ResourceManager.GetString("latestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENTLY SHOPPING IN:.
        /// </summary>
        public static string mainPageTitle {
            get {
                return ResourceManager.GetString("mainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new name.
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new shopping path.
        /// </summary>
        public static string newShopText {
            get {
                return ResourceManager.GetString("newShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new name.
        /// </summary>
        public static string newStoreName {
            get {
                return ResourceManager.GetString("newStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not signed in.
        /// </summary>
        public static string notSignedIn {
            get {
                return ResourceManager.GetString("notSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred store / brand / ....
        /// </summary>
        public static string preferredStore {
            get {
                return ResourceManager.GetString("preferredStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product category.
        /// </summary>
        public static string productCategory {
            get {
                return ResourceManager.GetString("productCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename {0}.
        /// </summary>
        public static string renameCategoryPageTitle {
            get {
                return ResourceManager.GetString("renameCategoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string renameCatText {
            get {
                return ResourceManager.GetString("renameCatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename shopping path.
        /// </summary>
        public static string renameShopText {
            get {
                return ResourceManager.GetString("renameShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename {0}.
        /// </summary>
        public static string renameStorePageTitle {
            get {
                return ResourceManager.GetString("renameStorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string saveButtonText {
            get {
                return ResourceManager.GetString("saveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a shopping path.
        /// </summary>
        public static string scratchButton {
            get {
                return ResourceManager.GetString("scratchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or start with an empty database..
        /// </summary>
        public static string scratchDescription {
            get {
                return ResourceManager.GetString("scratchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first shopping path..
        /// </summary>
        public static string scratchDescription1 {
            get {
                return ResourceManager.GetString("scratchDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start from scratch.
        /// </summary>
        public static string scratchHeader {
            get {
                return ResourceManager.GetString("scratchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send email.
        /// </summary>
        public static string sendEmailMenu {
            get {
                return ResourceManager.GetString("sendEmailMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settingsMenu {
            get {
                return ResourceManager.GetString("settingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE SHOPPING LIST.
        /// </summary>
        public static string settingsPageHeader {
            get {
                return ResourceManager.GetString("settingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string settingsPageName {
            get {
                return ResourceManager.GetString("settingsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY SHOPPING PATHS.
        /// </summary>
        public static string shopConfigurationPageName {
            get {
                return ResourceManager.GetString("shopConfigurationPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of the shopping path.
        /// </summary>
        public static string shopNameText {
            get {
                return ResourceManager.GetString("shopNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my shopping paths.
        /// </summary>
        public static string shopsConfigMenu {
            get {
                return ResourceManager.GetString("shopsConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign in.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign out.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complete network communication is secure. Your data remain private, protected with your Microsoft account. We save them to your SkyDrive here: 
        ///home &gt; AppData &gt; OneFamily &gt; ShoppingList
        ///.
        /// </summary>
        public static string skyDriveLocationHint {
            get {
                return ResourceManager.GetString("skyDriveLocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with your Microsoft account in order to save your shopping list to SkyDrive, sync them with your other devices or restore them in future on your new phone.
        ///Use the same account on all devices which you want to keep in sync..
        /// </summary>
        public static string skyDriveSyncInfo {
            get {
                return ResourceManager.GetString("skyDriveSyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic sync on app start and stop.
        /// </summary>
        public static string skyDriveSyncText {
            get {
                return ResourceManager.GetString("skyDriveSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted for: .
        /// </summary>
        public static string sortedFor {
            get {
                return ResourceManager.GetString("sortedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join syncing, and you&apos;re done!.
        /// </summary>
        public static string syncButton {
            get {
                return ResourceManager.GetString("syncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        public static string syncButtonText {
            get {
                return ResourceManager.GetString("syncButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already synced your database before?.
        /// </summary>
        public static string syncDescription {
            get {
                return ResourceManager.GetString("syncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronization.
        /// </summary>
        public static string syncHeader {
            get {
                return ResourceManager.GetString("syncHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit size.
        /// </summary>
        public static string unitSize {
            get {
                return ResourceManager.GetString("unitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move up.
        /// </summary>
        public static string upText {
            get {
                return ResourceManager.GetString("upText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping list is empty..
        /// </summary>
        public static string yourListEmpty {
            get {
                return ResourceManager.GetString("yourListEmpty", resourceCulture);
            }
        }
    }
}
