//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneShoppingList.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneShoppingList.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help and about ähnelt.
        /// </summary>
        public static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft account (live ID) ähnelt.
        /// </summary>
        public static string accountName {
            get {
                return ResourceManager.GetString("accountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string addButtonText {
            get {
                return ResourceManager.GetString("addButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add items by keyboard ähnelt.
        /// </summary>
        public static string addItemManually {
            get {
                return ResourceManager.GetString("addItemManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add items to your shopping list ähnelt.
        /// </summary>
        public static string addItemTitle {
            get {
                return ResourceManager.GetString("addItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add new product ähnelt.
        /// </summary>
        public static string addProductTitle {
            get {
                return ResourceManager.GetString("addProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add new shopping path ähnelt.
        /// </summary>
        public static string addShopPageTitle {
            get {
                return ResourceManager.GetString("addShopPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all ähnelt.
        /// </summary>
        public static string allShopsLabel {
            get {
                return ResourceManager.GetString("allShopsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all ähnelt.
        /// </summary>
        public static string allTitle {
            get {
                return ResourceManager.GetString("allTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ONE SHOPPING LIST ähnelt.
        /// </summary>
        public static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shopping List ähnelt.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die attention ähnelt.
        /// </summary>
        public static string attentionText {
            get {
                return ResourceManager.GetString("attentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die basket ähnelt.
        /// </summary>
        public static string basketButtonText {
            get {
                return ResourceManager.GetString("basketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die shopping basket ähnelt.
        /// </summary>
        public static string basketPageTitle {
            get {
                return ResourceManager.GetString("basketPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die buy ähnelt.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string cancelButtonText {
            get {
                return ResourceManager.GetString("cancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The category &apos;{0}&apos; already exists. Do you want to merge the two categories? ähnelt.
        /// </summary>
        public static string categoryMergeDialog {
            get {
                return ResourceManager.GetString("categoryMergeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checkmark items in lists ähnelt.
        /// </summary>
        public static string checkInList {
            get {
                return ResourceManager.GetString("checkInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clear shopping list ähnelt.
        /// </summary>
        public static string clearListMenu {
            get {
                return ResourceManager.GetString("clearListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I am sorry, but I could not connect to your OneDrive. Please try to log in again on the Settings page of this App. ähnelt.
        /// </summary>
        public static string connectionErrorMessage {
            get {
                return ResourceManager.GetString("connectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Others ähnelt.
        /// </summary>
        public static string defaultCategory {
            get {
                return ResourceManager.GetString("defaultCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content/EN-DefaultItemList.json ähnelt.
        /// </summary>
        public static string defaultItemList {
            get {
                return ResourceManager.GetString("defaultItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content/EN-DefaultShopList.json ähnelt.
        /// </summary>
        public static string defaultShopList {
            get {
                return ResourceManager.GetString("defaultShopList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pcs ähnelt.
        /// </summary>
        public static string defaultUnit {
            get {
                return ResourceManager.GetString("defaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string deleteButtonText {
            get {
                return ResourceManager.GetString("deleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to delete {0}. ähnelt.
        /// </summary>
        public static string deleteElementConfirmation {
            get {
                return ResourceManager.GetString("deleteElementConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are about to clear your shopping list. ähnelt.
        /// </summary>
        public static string deleteListConfirmation {
            get {
                return ResourceManager.GetString("deleteListConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete shopping path ähnelt.
        /// </summary>
        public static string deleteShopText {
            get {
                return ResourceManager.GetString("deleteShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die move down ähnelt.
        /// </summary>
        public static string downText {
            get {
                return ResourceManager.GetString("downText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit ähnelt.
        /// </summary>
        public static string editButtonText {
            get {
                return ResourceManager.GetString("editButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit {0} ähnelt.
        /// </summary>
        public static string editProduct {
            get {
                return ResourceManager.GetString("editProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shopping List ähnelt.
        /// </summary>
        public static string emailSubject {
            get {
                return ResourceManager.GetString("emailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die favorites ähnelt.
        /// </summary>
        public static string favButtonText {
            get {
                return ResourceManager.GetString("favButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die favorites ähnelt.
        /// </summary>
        public static string favoritesTitle {
            get {
                return ResourceManager.GetString("favoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die help &amp; about ähnelt.
        /// </summary>
        public static string helpAndAbout {
            get {
                return ResourceManager.GetString("helpAndAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HOW WOULD YOU LIKE TO START? ähnelt.
        /// </summary>
        public static string howToStart {
            get {
                return ResourceManager.GetString("howToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string importButton {
            get {
                return ResourceManager.GetString("importButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to start with a small database? ähnelt.
        /// </summary>
        public static string importDescription {
            get {
                return ResourceManager.GetString("importDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import some sample data ähnelt.
        /// </summary>
        public static string importHeader {
            get {
                return ResourceManager.GetString("importHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It contains usual products: Milk, Butter, Apples, ... ähnelt.
        /// </summary>
        public static string importPicker {
            get {
                return ResourceManager.GetString("importPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die initial setup ähnelt.
        /// </summary>
        public static string initialSetupPageTitle {
            get {
                return ResourceManager.GetString("initialSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I recommend you this App: ähnelt.
        /// </summary>
        public static string IrecommendYou {
            get {
                return ResourceManager.GetString("IrecommendYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} added to your list ähnelt.
        /// </summary>
        public static string itemAdded {
            get {
                return ResourceManager.GetString("itemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  items ähnelt.
        /// </summary>
        public static string itemsName {
            get {
                return ResourceManager.GetString("itemsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die recent ähnelt.
        /// </summary>
        public static string latestTitle {
            get {
                return ResourceManager.GetString("latestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bug or suggestion ähnelt.
        /// </summary>
        public static string mailToAuthor {
            get {
                return ResourceManager.GetString("mailToAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Share ähnelt.
        /// </summary>
        public static string mailToFriend {
            get {
                return ResourceManager.GetString("mailToFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CURRENTLY SHOPPING IN: ähnelt.
        /// </summary>
        public static string mainPageTitle {
            get {
                return ResourceManager.GetString("mainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings &amp; more ähnelt.
        /// </summary>
        public static string moreMenuItem {
            get {
                return ResourceManager.GetString("moreMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more ähnelt.
        /// </summary>
        public static string morePageTitle {
            get {
                return ResourceManager.GetString("morePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new name ähnelt.
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new in this version ähnelt.
        /// </summary>
        public static string newInThisVersion {
            get {
                return ResourceManager.GetString("newInThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new shopping path ähnelt.
        /// </summary>
        public static string newShopText {
            get {
                return ResourceManager.GetString("newShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new name ähnelt.
        /// </summary>
        public static string newStoreName {
            get {
                return ResourceManager.GetString("newStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No network available. ähnelt.
        /// </summary>
        public static string NoNetworkAvailable {
            get {
                return ResourceManager.GetString("NoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not signed in ähnelt.
        /// </summary>
        public static string notSignedIn {
            get {
                return ResourceManager.GetString("notSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die my other apps ähnelt.
        /// </summary>
        public static string otherApps {
            get {
                return ResourceManager.GetString("otherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die preferred brand / store / ... ähnelt.
        /// </summary>
        public static string preferredStore {
            get {
                return ResourceManager.GetString("preferredStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die product category ähnelt.
        /// </summary>
        public static string productCategory {
            get {
                return ResourceManager.GetString("productCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die product name ähnelt.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die quantity ähnelt.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rate ähnelt.
        /// </summary>
        public static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename {0} ähnelt.
        /// </summary>
        public static string renameCategoryPageTitle {
            get {
                return ResourceManager.GetString("renameCategoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit ähnelt.
        /// </summary>
        public static string renameCatText {
            get {
                return ResourceManager.GetString("renameCatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename shopping path ähnelt.
        /// </summary>
        public static string renameShopText {
            get {
                return ResourceManager.GetString("renameShopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename {0} ähnelt.
        /// </summary>
        public static string renameStorePageTitle {
            get {
                return ResourceManager.GetString("renameStorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die save ähnelt.
        /// </summary>
        public static string saveButtonText {
            get {
                return ResourceManager.GetString("saveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a shopping path ähnelt.
        /// </summary>
        public static string scratchButton {
            get {
                return ResourceManager.GetString("scratchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Or start with an empty database. ähnelt.
        /// </summary>
        public static string scratchDescription {
            get {
                return ResourceManager.GetString("scratchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create your first shopping path. ähnelt.
        /// </summary>
        public static string scratchDescription1 {
            get {
                return ResourceManager.GetString("scratchDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die start from scratch ähnelt.
        /// </summary>
        public static string scratchHeader {
            get {
                return ResourceManager.GetString("scratchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die send email ähnelt.
        /// </summary>
        public static string sendEmailMenu {
            get {
                return ResourceManager.GetString("sendEmailMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string settingsMenu {
            get {
                return ResourceManager.GetString("settingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ONE SHOPPING LIST ähnelt.
        /// </summary>
        public static string settingsPageHeader {
            get {
                return ResourceManager.GetString("settingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SETTINGS ähnelt.
        /// </summary>
        public static string settingsPageName {
            get {
                return ResourceManager.GetString("settingsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MY SHOPPING PATHS ähnelt.
        /// </summary>
        public static string shopConfigurationPageName {
            get {
                return ResourceManager.GetString("shopConfigurationPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name of the shopping path ähnelt.
        /// </summary>
        public static string shopNameText {
            get {
                return ResourceManager.GetString("shopNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die my shopping paths ähnelt.
        /// </summary>
        public static string shopsConfigMenu {
            get {
                return ResourceManager.GetString("shopsConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show all ähnelt.
        /// </summary>
        public static string showAllButtonCaption {
            get {
                return ResourceManager.GetString("showAllButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} items on your shopping list are not available at {1}. ähnelt.
        /// </summary>
        public static string showAllExplanation {
            get {
                return ResourceManager.GetString("showAllExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One Item on your shopping list is not available at {0}. ähnelt.
        /// </summary>
        public static string showAllExplanationOne {
            get {
                return ResourceManager.GetString("showAllExplanationOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        public static string showLessButtonCaption {
            get {
                return ResourceManager.GetString("showLessButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sign in ähnelt.
        /// </summary>
        public static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sign out ähnelt.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The complete network communication is secure. Your data remain private, protected with your Microsoft account. We save them to your OneDrive here: 
        ///home &gt; AppData &gt; OneFamily &gt; ShoppingList
        /// ähnelt.
        /// </summary>
        public static string skyDriveLocationHint {
            get {
                return ResourceManager.GetString("skyDriveLocationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign in with your Microsoft account in order to save your data to OneDrive, sync them with your other devices or restore them in future on your new phone.
        ///Use the same account on all devices which you want to keep in sync. ähnelt.
        /// </summary>
        public static string skyDriveSyncInfo {
            get {
                return ResourceManager.GetString("skyDriveSyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic sync on app start and stop ähnelt.
        /// </summary>
        public static string skyDriveSyncText {
            get {
                return ResourceManager.GetString("skyDriveSyncText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorted for:  ähnelt.
        /// </summary>
        public static string sortedFor {
            get {
                return ResourceManager.GetString("sortedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die support ähnelt.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Join syncing, and you&apos;re done! ähnelt.
        /// </summary>
        public static string syncButton {
            get {
                return ResourceManager.GetString("syncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sync now ähnelt.
        /// </summary>
        public static string syncButtonText {
            get {
                return ResourceManager.GetString("syncButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already synced your database before? ähnelt.
        /// </summary>
        public static string syncDescription {
            get {
                return ResourceManager.GetString("syncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die synchronization ähnelt.
        /// </summary>
        public static string syncHeader {
            get {
                return ResourceManager.GetString("syncHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sync ähnelt.
        /// </summary>
        public static string syncSettingsHeader {
            get {
                return ResourceManager.GetString("syncSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tools ähnelt.
        /// </summary>
        public static string toolsSettingsHeader {
            get {
                return ResourceManager.GetString("toolsSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unit size ähnelt.
        /// </summary>
        public static string unitSize {
            get {
                return ResourceManager.GetString("unitSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die move up ähnelt.
        /// </summary>
        public static string upText {
            get {
                return ResourceManager.GetString("upText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vote next feature ähnelt.
        /// </summary>
        public static string voteNextFeature {
            get {
                return ResourceManager.GetString("voteNextFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WELCOME ähnelt.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your shopping list is empty. ähnelt.
        /// </summary>
        public static string yourListEmpty {
            get {
                return ResourceManager.GetString("yourListEmpty", resourceCulture);
            }
        }
    }
}
